IF
	!AreaCheck("UT0000")
	!AreaCheck("TR0000")
	!AreaCheck("TR0001")
	!AreaCheck("TR0002")
	!AreaCheck("TR0003")
THEN
	RESPONSE #100
		StorePartyLocations()
		ClearAllActions()
		DestroySelf()
		StartCutSceneMode()
		StartCutScene("UTCutR1")
END

IF
	Global("ExitArenaMovie","GLOBAL",1)
	OR(5)
		AreaCheck("UT0000")
		AreaCheck("TR0000")
		AreaCheck("TR0001")
		AreaCheck("TR0002")
		AreaCheck("TR0003")
THEN
	RESPONSE #100
		DestroySelf()
		StartCutSceneMode()
		StartCutScene("CUT202Y")
END

IF
	AreaCheck("UT0000")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,@99995)
		DestroySelf()
END

IF
	OR(4)
		!AreaCheck("TR0000")
		!AreaCheck("TR0001")
		!AreaCheck("TR0002")
		!AreaCheck("TR0003")
THEN
	RESPONSE #100
		DestroySelf()
END

IF
	True()
THEN
	RESPONSE #100
		DestroySelf()
END

