IF
	!Global("ExitArenaMovie","GLOBAL",1)
	!AreaCheck("UT0000")
	!AreaCheck("TR0000")
	!AreaCheck("TR0001")
	!AreaCheck("TR0002")
	!AreaCheck("TR0003")
THEN
	RESPONSE #100
		StorePartyLocations()
		ClearAllActions()
		DestroySelf()
		StartCutSceneMode()
		StartCutScene("UTCutR1")
END

IF
	!Global("ExitArenaMovie","GLOBAL",1)
	AreaCheck("UT0000")
THEN
	RESPONSE #100
		DisplayStringHead(Player1,@99995)
		DestroySelf()
END

IF
	Global("ExitArenaMovie","GLOBAL",1)
	!AreaCheck("UT0000")
	!AreaCheck("TR0000")
	!AreaCheck("TR0001")
	!AreaCheck("TR0002")
	!AreaCheck("TR0003")
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		CutSceneId(Player1)
		MoveViewObject(Player1,INSTANT)
		FadeFromColor([60.0],0)
		CreateVisualEffectObject("UTTele1",Player1)
		CreateVisualEffectObject("UTTele1",Player2)
		CreateVisualEffectObject("UTTele1",Player3)
		CreateVisualEffectObject("UTTele1",Player4)
		CreateVisualEffectObject("UTTele1",Player5)
		CreateVisualEffectObject("UTTele1",Player6)
		SmallWait(40)
		SetGlobal("ExitArenaMovie","GLOBAL",0)
		EndCutSceneMode()
		DestroySelf()
END

IF
	Global("ExitArenaMovie","GLOBAL",1)
	OR(5)
		AreaCheck("UT0000")
		AreaCheck("TR0000")
		AreaCheck("TR0001")
		AreaCheck("TR0002")
		AreaCheck("TR0003")
THEN
	RESPONSE #100
		DestroySelf()
		StartCutSceneMode()
		StartCutScene("UTCutR3")
END

IF
	True()
THEN
	RESPONSE #100
		DestroySelf()
END
